In [6]:
# Install datasets Library (if not already installed)
# !pip install -U datasets

# Importing Libraries

import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])
df.iloc[0:10]

df_filled = df
df_unique = df_filled
df_unique = df_unique.drop_duplicates(subset=['job_title', 'company_name'])  


print('length of original df:             ',    len(df_filled)) 
print('length of drop duplicates df:       ',    len(df_unique))
print('rows dropped:                         ', len(df_filled)-len(df_unique))

length of original df:              785741
length of drop duplicates df:        508042
rows dropped:                          277699

In [7]:
df.head

<bound method NDFrame.head of              job_title_short  \
0       Senior Data Engineer
1               Data Analyst
2              Data Engineer
3              Data Engineer
4              Data Engineer
...                      ...
785736     Software Engineer
785737          Data Analyst
785738      Business Analyst
785739         Data Engineer
785740     Software Engineer

                                                job_title  \
0       Senior Clinical Data Engineer / Principal Clin...
1                                            Data Analyst
2       Data Engineer/Scientist/Analyst, Mid or Senior...
3       LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...
4                                  Data Engineer- Sr Jobs
...                                                   ...
785736                                    DevOps Engineer
785737                                   CRM Data Analyst
785738                     Commercial Analyst - Start Now
785739  Principal Associate, Data Engineer (Remote-Eli...
785740                                 AWS System Analyst

                               job_location                    job_via  \
0                             Watertown, CT            via Work Nearby
1              Guadalajara, Jalisco, Mexico           via BeBee México
2                           Berlin, Germany               via LinkedIn
3                           San Antonio, TX          via Diversity.com
4                            Washington, DC         via Clearance Jobs
...                                     ...                        ...
785736                            Singapura        melalui Trabajo.org
785737                   Bad Rodach, Jerman  melalui BeBee Deutschland
785738                             Malaysia           melalui Ricebowl
785739  Newark, New Jersey, Amerika Serikat        melalui Recruit.net
785740                                India             melalui Trigyn

       job_schedule_type  job_work_from_home       search_location  \
0              Full-time               False  Texas, United States
1              Full-time               False                Mexico
2              Full-time               False               Germany
3              Full-time               False  Texas, United States
4              Full-time               False                 Sudan
...                  ...                 ...                   ...
785736   Pekerjaan tetap               False             Singapore
785737   Pekerjaan tetap               False               Germany
785738   Pekerjaan tetap               False              Malaysia
785739   Pekerjaan tetap               False                 Sudan
785740   Pekerjaan tetap               False                 India

           job_posted_date  job_no_degree_mention  job_health_insurance  \
0      2023-06-16 13:44:15                  False                 False
1      2023-01-14 13:18:07                  False                 False
2      2023-10-10 13:14:55                  False                 False
3      2023-07-04 13:01:41                   True                 False
4      2023-08-07 14:29:36                  False                 False
...                    ...                    ...                   ...
785736 2023-03-13 06:16:16                  False                 False
785737 2023-03-12 06:18:18                  False                 False
785738 2023-03-12 06:32:36                  False                 False
785739 2023-03-12 06:32:15                  False                 False
785740 2023-03-13 06:16:31                  False                 False

          job_country salary_rate  salary_year_avg  salary_hour_avg  \
0       United States         NaN              NaN              NaN
1              Mexico         NaN              NaN              NaN
2             Germany         NaN              NaN              NaN
3       United States         NaN              NaN              NaN
4               Sudan         NaN              NaN              NaN
...               ...         ...              ...              ...
785736      Singapore         NaN              NaN              NaN
785737        Germany         NaN              NaN              NaN
785738       Malaysia         NaN              NaN              NaN
785739          Sudan         NaN              NaN              NaN
785740          India         NaN              NaN              NaN

                              company_name  \
0                     Boehringer Ingelheim
1               Hewlett Packard Enterprise
2                 ALPHA Augmented Services
3             Southwest Research Institute
4                          Kristina Daniel
...                                    ...
785736  CAREERSTAR INTERNATIONAL PTE. LTD.
785737                    HABA FAMILYGROUP
785738               Lendlease Corporation
785739                         Capital One
785740                              Trigyn

                                               job_skills  \
0                                                     NaN
1       ['r', 'python', 'sql', 'nosql', 'power bi', 't...
2       ['python', 'sql', 'c#', 'azure', 'airflow', 'd...
3       ['python', 'c++', 'java', 'matlab', 'aws', 'te...
4       ['bash', 'python', 'oracle', 'aws', 'ansible',...
...                                                   ...
785736  ['bash', 'python', 'perl', 'linux', 'unix', 'k...
785737                     ['sas', 'sas', 'sql', 'excel']
785738                            ['powerpoint', 'excel']
785739  ['python', 'go', 'nosql', 'sql', 'mongo', 'she...
785740                                    ['aws', 'flow']

                                          job_type_skills
0                                                     NaN
1       {'analyst_tools': ['power bi', 'tableau'], 'pr...
2       {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3       {'cloud': ['aws'], 'libraries': ['tensorflow',...
4       {'cloud': ['oracle', 'aws'], 'other': ['ansibl...
...                                                   ...
785736  {'os': ['linux', 'unix'], 'other': ['kubernete...
785737  {'analyst_tools': ['sas', 'excel'], 'programmi...
785738         {'analyst_tools': ['powerpoint', 'excel']}
785739  {'cloud': ['aws', 'snowflake', 'azure', 'redsh...
785740              {'cloud': ['aws'], 'other': ['flow']}

[785741 rows x 17 columns]>

In [8]:
df.tail

<bound method NDFrame.tail of              job_title_short  \
0       Senior Data Engineer
1               Data Analyst
2              Data Engineer
3              Data Engineer
4              Data Engineer
...                      ...
785736     Software Engineer
785737          Data Analyst
785738      Business Analyst
785739         Data Engineer
785740     Software Engineer

                                                job_title  \
0       Senior Clinical Data Engineer / Principal Clin...
1                                            Data Analyst
2       Data Engineer/Scientist/Analyst, Mid or Senior...
3       LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...
4                                  Data Engineer- Sr Jobs
...                                                   ...
785736                                    DevOps Engineer
785737                                   CRM Data Analyst
785738                     Commercial Analyst - Start Now
785739  Principal Associate, Data Engineer (Remote-Eli...
785740                                 AWS System Analyst

                               job_location                    job_via  \
0                             Watertown, CT            via Work Nearby
1              Guadalajara, Jalisco, Mexico           via BeBee México
2                           Berlin, Germany               via LinkedIn
3                           San Antonio, TX          via Diversity.com
4                            Washington, DC         via Clearance Jobs
...                                     ...                        ...
785736                            Singapura        melalui Trabajo.org
785737                   Bad Rodach, Jerman  melalui BeBee Deutschland
785738                             Malaysia           melalui Ricebowl
785739  Newark, New Jersey, Amerika Serikat        melalui Recruit.net
785740                                India             melalui Trigyn

       job_schedule_type  job_work_from_home       search_location  \
0              Full-time               False  Texas, United States
1              Full-time               False                Mexico
2              Full-time               False               Germany
3              Full-time               False  Texas, United States
4              Full-time               False                 Sudan
...                  ...                 ...                   ...
785736   Pekerjaan tetap               False             Singapore
785737   Pekerjaan tetap               False               Germany
785738   Pekerjaan tetap               False              Malaysia
785739   Pekerjaan tetap               False                 Sudan
785740   Pekerjaan tetap               False                 India

           job_posted_date  job_no_degree_mention  job_health_insurance  \
0      2023-06-16 13:44:15                  False                 False
1      2023-01-14 13:18:07                  False                 False
2      2023-10-10 13:14:55                  False                 False
3      2023-07-04 13:01:41                   True                 False
4      2023-08-07 14:29:36                  False                 False
...                    ...                    ...                   ...
785736 2023-03-13 06:16:16                  False                 False
785737 2023-03-12 06:18:18                  False                 False
785738 2023-03-12 06:32:36                  False                 False
785739 2023-03-12 06:32:15                  False                 False
785740 2023-03-13 06:16:31                  False                 False

          job_country salary_rate  salary_year_avg  salary_hour_avg  \
0       United States         NaN              NaN              NaN
1              Mexico         NaN              NaN              NaN
2             Germany         NaN              NaN              NaN
3       United States         NaN              NaN              NaN
4               Sudan         NaN              NaN              NaN
...               ...         ...              ...              ...
785736      Singapore         NaN              NaN              NaN
785737        Germany         NaN              NaN              NaN
785738       Malaysia         NaN              NaN              NaN
785739          Sudan         NaN              NaN              NaN
785740          India         NaN              NaN              NaN

                              company_name  \
0                     Boehringer Ingelheim
1               Hewlett Packard Enterprise
2                 ALPHA Augmented Services
3             Southwest Research Institute
4                          Kristina Daniel
...                                    ...
785736  CAREERSTAR INTERNATIONAL PTE. LTD.
785737                    HABA FAMILYGROUP
785738               Lendlease Corporation
785739                         Capital One
785740                              Trigyn

                                               job_skills  \
0                                                     NaN
1       ['r', 'python', 'sql', 'nosql', 'power bi', 't...
2       ['python', 'sql', 'c#', 'azure', 'airflow', 'd...
3       ['python', 'c++', 'java', 'matlab', 'aws', 'te...
4       ['bash', 'python', 'oracle', 'aws', 'ansible',...
...                                                   ...
785736  ['bash', 'python', 'perl', 'linux', 'unix', 'k...
785737                     ['sas', 'sas', 'sql', 'excel']
785738                            ['powerpoint', 'excel']
785739  ['python', 'go', 'nosql', 'sql', 'mongo', 'she...
785740                                    ['aws', 'flow']

                                          job_type_skills
0                                                     NaN
1       {'analyst_tools': ['power bi', 'tableau'], 'pr...
2       {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3       {'cloud': ['aws'], 'libraries': ['tensorflow',...
4       {'cloud': ['oracle', 'aws'], 'other': ['ansibl...
...                                                   ...
785736  {'os': ['linux', 'unix'], 'other': ['kubernete...
785737  {'analyst_tools': ['sas', 'excel'], 'programmi...
785738         {'analyst_tools': ['powerpoint', 'excel']}
785739  {'cloud': ['aws', 'snowflake', 'azure', 'redsh...
785740              {'cloud': ['aws'], 'other': ['flow']}

[785741 rows x 17 columns]>

In [9]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
159051,Data Engineer,"Powered Data Engineer, Senior Consultant",Singapore,via Jooble,Full-time,False,Singapore,2023-07-13 08:13:06,True,False,Singapore,NaN,NaN,NaN,Kpmg Services Pte. Ltd.,"['sql', 'jira']","{'async': ['jira'], 'programming': ['sql']}"
312966,Data Analyst,Lead BI Engineer,"Dublin, Ireland",via Trabajo.org,Full-time,False,Ireland,2023-03-05 17:40:12,True,False,Ireland,NaN,NaN,NaN,CPL Recruitment,"['sql', 'sql server', 'azure', 'ssis', 'power ...","{'analyst_tools': ['ssis', 'power bi', 'ssrs']..."
207331,Data Analyst,Freelance Data Analist,Netherlands,via BeBee,Temp work,False,Netherlands,2023-11-17 22:26:05,True,False,Netherlands,NaN,NaN,NaN,Netherlands,NaN,NaN
624814,Senior Data Scientist,Senior Data Scientist,Thailand,via LinkedIn,Full-time,False,Thailand,2023-04-26 12:38:45,False,False,Thailand,NaN,NaN,NaN,Gosoft (Thailand),"['sql', 'python', 'pandas', 'spark']","{'libraries': ['pandas', 'spark'], 'programmin..."
509014,Data Analyst,Data Analyst,Hong Kong,via Indeed HK,Full-time,False,Hong Kong,2023-03-08 11:57:14,True,False,Hong Kong,NaN,NaN,NaN,中国太平,"['excel', 'word', 'powerpoint']","{'analyst_tools': ['excel', 'word', 'powerpoin..."
351807,Data Analyst,Data Analyst,"Holly Hill, SC",via Recruit.net,Full-time,False,Georgia,2023-07-19 23:32:56,False,False,United States,NaN,NaN,NaN,Kavaliro,"['sql', 'excel', 'tableau']","{'analyst_tools': ['excel', 'tableau'], 'progr..."
102698,Data Engineer,Data Engineer,Singapore,via Recruit.net,Full-time,False,Singapore,2023-07-21 00:18:06,False,False,Singapore,NaN,NaN,NaN,Datahondo Pte. Ltd.,"['java', 'sql', 'aws', 'azure', 'hadoop', 'spa...","{'cloud': ['aws', 'azure'], 'libraries': ['had..."
33243,Data Analyst,Data Analyst - Stage,"Paris, France",via Jobijoba,Full-time,False,France,2023-07-14 13:27:25,False,False,France,NaN,NaN,NaN,Beanstock,['sql'],{'programming': ['sql']}
9555,Data Engineer,AWS Data Engineer,"Malvern, PA",via LinkedIn,Full-time,False,"Illinois, United States",2023-10-19 13:30:12,False,False,United States,NaN,NaN,NaN,Nityo Infotech,['aws'],{'cloud': ['aws']}
540643,Senior Data Analyst,Senior Database Analyst,Singapore,via LinkedIn,Full-time,False,Singapore,2023-05-16 19:35:18,False,False,Singapore,NaN,NaN,NaN,CLOUDUN TECHNOLOGY PTE. LTD.,"['sas', 'sas', 'r', 'mongodb', 'mongodb', 'mys...","{'analyst_tools': ['sas', 'spss'], 'cloud': ['..."

In [10]:
df.sample(10, random_state=42)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,NaN,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,NaN,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,NaN,NaN,NaN,Morgan King,NaN,NaN
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,NaN,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,NaN,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}
183426,Data Analyst,Data Analyst,Singapore,via Singapore | JobsDB,Full-time,False,Singapore,2023-11-09 16:07:57,False,False,Singapore,NaN,NaN,NaN,FLEXOSENSE PTE. LTD.,"['r', 'python', 'java', 'sql', 'sql server', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
287790,Data Analyst,Data Analyst,"Tampa, FL",via LinkedIn,Full-time,False,"Florida, United States",2023-07-14 17:02:23,True,False,United States,NaN,NaN,NaN,Iris Software Inc.,"['sql', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
541983,Data Analyst,"Data Analyst, Cloud Systems Jobs","Chantilly, VA",via Clearance Jobs,Full-time,False,Georgia,2023-06-15 19:44:34,False,False,United States,NaN,NaN,NaN,SAIC,"['sql', 'r', 'matlab', 'python', 'oracle', 'aw...","{'analyst_tools': ['power bi', 'tableau', 'qli..."
416896,Data Scientist,Alternant Actuariat & Data Science H/F,France,via LinkedIn,Full-time,False,France,2023-09-22 16:47:24,False,False,France,NaN,NaN,NaN,KPMG France,NaN,NaN
780907,Data Engineer,"Data Engineer with Fivetran,Qlik Must","Mexico City, CDMX, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-16 06:19:09,False,False,Mexico,NaN,NaN,NaN,CORUS Consulting,"['oracle', 'snowflake', 'aws', 'azure', 'alter...","{'analyst_tools': ['alteryx'], 'cloud': ['orac..."

In [11]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

In [29]:
df_altered = df_original.copy()

In [31]:
print('Id of df_original                ', id(df_original) )
print('Id of df_altered                 ', id(df_altered))
print('Are the two dataframes the same?         ', id(df_original) == id(df_altered))

Id of df_original                 14369385232
Id of df_altered                  5661708176
Are the two dataframes the same?          False